version: 2
jobs:
  build:
    docker:
      - image: kemenaran/rgbds:0.4.0
    steps:
      - checkout
      - run:
          name: Building
          command: make build
      - run:
          name: Testing checksum
          command: make test
