version: 2
jobs:
  build:
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout
      - run:
          name: build rgbds
          command: |
            # Install build dependencies
            sudo apt update && sudo install -y build-essential byacc flex pkg-config libpng-dev

            # Retrieve rgbds
            git clone --depth 1 --branch v0.4.0 https://github.com/rednex/rgbds.git /tmp/rgbds

            # Build rgbds
            cd /tmp/rgbds
            sudo make
            sudo make install

      - run:
          name: Building
          command: make build
      - run:
          name: Testing checksum
          command: make test
